# Generated by Django 6.0.1 on 2026-02-03 12:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('TECH', 'Tech'), ('VOCATIONAL', 'Vocational'), ('CRAFT', 'Craft')], default=None, max_length=200, null=True, unique=True)),
                ('descriptions', models.TextField(blank=True, max_length=1000, null=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SkillCategory',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('skill_difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
                ('min_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5, message="Min age shouldn't be less than 5 "), django.core.validators.MaxValueValidator(15, message="Max age shouldn't be grater than 15")])),
                ('max_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5, message="Min age shouldn't be less than 5 "), django.core.validators.MaxValueValidator(15, message="Max age shouldn't be grater than 15")])),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='skills.skillcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='skillcategory',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='skillcategory',
            index=models.Index(fields=['category_id'], name='category_id_idx'),
        ),
        migrations.AddIndex(
            model_name='skills',
            index=models.Index(fields=['is_active'], name='is_active'),
        ),
        migrations.AddIndex(
            model_name='skills',
            index=models.Index(fields=['is_deleted'], name='deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='skills',
            index=models.Index(fields=['name'], name='skill_name_idx'),
        ),
        migrations.AddIndex(
            model_name='skills',
            index=models.Index(fields=['is_active', 'is_deleted'], name='deleted_active_idx'),
        ),
    ]
