# Generated by Django 6.0.1 on 2026-02-04 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0007_alter_childinterest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrol_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='users.childprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='skills.skills')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_active'], name='ac_idx'), models.Index(fields=['enrol_id'], name='enrol_idx')],
                'constraints': [models.UniqueConstraint(fields=('child_profile', 'skill'), name='unique_profile_and_skill')],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('purchase_status', models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('COMPLETEED', 'Completed')], default='PENDING', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tx_ref', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('purchased_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='users.childprofile')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='skills.skills')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purchase_id'], name='skills_purc_purchas_41165e_idx'), models.Index(fields=['tx_ref'], name='skills_purc_tx_ref_ecd2f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('tx_ref',), name='unique_tx_ref_per_purchase')],
            },
        ),
    ]
