# Generated by Django 6.0.1 on 2026-02-16 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='child_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='users.childprofile'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchased_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchased_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='users.childprofile'),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skills',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='skills.skillcategory'),
        ),
        migrations.AddField(
            model_name='skills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='skills.skills'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='skills.skills'),
        ),
        migrations.AddIndex(
            model_name='skillcategory',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='skillcategory',
            index=models.Index(fields=['category_id'], name='category_id_idx'),
        ),
        migrations.AddIndex(
            model_name='skills',
            index=models.Index(fields=['is_active'], name='is_active'),
        ),
        migrations.AddIndex(
            model_name='skills',
            index=models.Index(fields=['is_deleted'], name='deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='skills',
            index=models.Index(fields=['name'], name='skill_name_idx'),
        ),
        migrations.AddIndex(
            model_name='skills',
            index=models.Index(fields=['is_active', 'is_deleted'], name='deleted_active_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_id'], name='skills_purc_purchas_41165e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['tx_ref'], name='skills_purc_tx_ref_ecd2f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('tx_ref',), name='unique_tx_ref_per_purchase'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('skill', 'purchased_for'), name='unique_purchase_id'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['is_active'], name='ac_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrol_id'], name='enrol_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('child_profile', 'skill'), name='unique_profile_and_skill'),
        ),
    ]
