# Generated by Django 6.0.1 on 2026-02-16 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('user_role', models.CharField(blank=True, choices=[('INSTRUCTOR', 'Instructor'), ('GUARDIAN', 'Guardian')], default=None, max_length=200, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('active_profile', models.CharField(blank=True, choices=[('CHILD', 'Child'), ('GUARDIAN', 'Guardian')], default=None, max_length=200, null=True)),
                ('account_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=200)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('child_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default=None, max_length=200)),
                ('date_of_birth', models.DateField(blank=True)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChildInterest',
            fields=[
                ('interest_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='users.childprofile')),
            ],
            options={
                'verbose_name': 'Interest',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_account', to='users.childprofile'),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('guardian_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('certificate_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('issued_by', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.instructor')),
            ],
            options={
                'verbose_name': 'Certificate',
            },
        ),
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('otp_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_code', models.CharField(max_length=20, unique=True)),
                ('hash_code', models.CharField(max_length=200, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OneTimePassword',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('reset_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('reset_code', models.CharField(db_index=True, max_length=200)),
                ('reset_token', models.URLField(blank=True, db_index=True, null=True)),
                ('raw_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ResetPassword',
            },
        ),
        migrations.AddIndex(
            model_name='childprofile',
            index=models.Index(fields=['child_id'], name='id_idx'),
        ),
        migrations.AddIndex(
            model_name='childprofile',
            index=models.Index(fields=['is_active', 'is_deleted'], name='active_idx'),
        ),
        migrations.AddConstraint(
            model_name='childprofile',
            constraint=models.UniqueConstraint(fields=('child_id', 'guardian'), name='unique_child_guardian'),
        ),
        migrations.AddIndex(
            model_name='childinterest',
            index=models.Index(fields=['interest_id'], name='pk_idx'),
        ),
        migrations.AddIndex(
            model_name='childinterest',
            index=models.Index(fields=['is_active', 'is_deleted'], name='act_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'account_status'], name='active_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['created_at'], name='time_idx'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['is_active', 'is_deleted'], name='active_deleted_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificates',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_name_and_user'),
        ),
        migrations.AddIndex(
            model_name='onetimepassword',
            index=models.Index(fields=['hash_code'], name='hash_cde_idx'),
        ),
        migrations.AddIndex(
            model_name='onetimepassword',
            index=models.Index(fields=['is_active', 'is_used'], name='active_used_idx'),
        ),
        migrations.AddConstraint(
            model_name='onetimepassword',
            constraint=models.UniqueConstraint(fields=('user', 'hash_code'), name='unique_code_user'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['is_active'], name='is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordreset',
            index=models.Index(fields=['is_active', 'user', 'reset_code'], name='active_codes_idx'),
        ),
        migrations.AddConstraint(
            model_name='passwordreset',
            constraint=models.UniqueConstraint(fields=('reset_code', 'user'), name='unique_reset_code_user'),
        ),
        migrations.AddConstraint(
            model_name='passwordreset',
            constraint=models.UniqueConstraint(fields=('reset_token', 'user'), name='unique_reset_user_user'),
        ),
    ]
