# Generated by Django 6.0.1 on 2026-01-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(blank=True, choices=[('INSTRUCTOR', 'Instructor'), ('GUARDIAN', 'Guardian')], default=None, max_length=200, null=True),
        ),
    ]
