# Generated by Django 6.0.1 on 2026-01-27 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('otp_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hash_code', models.CharField(max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OneTimePassword',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hash_code'], name='hash_cde_idx'), models.Index(fields=['is_active', 'is_used'], name='active_used_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'hash_code'), name='unique_code_user')],
            },
        ),
    ]
