# Generated by Django 6.0.1 on 2026-01-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_onetimepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='hash_code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
