# Generated by Django 6.0.1 on 2026-01-30 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_onetimepassword_hash_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('reset_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('reset_code', models.CharField(db_index=True, max_length=200)),
                ('reset_token', models.URLField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ResetPassword',
                'indexes': [models.Index(fields=['is_active'], name='is_active_idx'), models.Index(fields=['is_active', 'user', 'reset_code'], name='active_codes_idx')],
                'constraints': [models.UniqueConstraint(fields=('reset_code', 'user'), name='unique_reset_code_user'), models.UniqueConstraint(fields=('reset_token', 'user'), name='unique_reset_user_user')],
            },
        ),
    ]
