# Generated by Django 6.0.1 on 2026-02-02 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_profile',
            field=models.CharField(choices=[('CHILD', 'Child'), ('GUARDIAN', 'Guardian')], default='GUARDIAN', max_length=200),
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('child_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default=None, max_length=200)),
                ('date_of_birth', models.DateField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': '-created_at',
            },
        ),
        migrations.CreateModel(
            name='ChildInterest',
            fields=[
                ('interest_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='users.childprofile')),
            ],
            options={
                'verbose_name': 'Interest',
                'ordering': '-created_at',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('guardian_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('certificate_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('issued_by', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.instructor')),
            ],
            options={
                'verbose_name': 'Certificate',
            },
        ),
        migrations.AddIndex(
            model_name='childprofile',
            index=models.Index(fields=['child_id'], name='id_idx'),
        ),
        migrations.AddIndex(
            model_name='childprofile',
            index=models.Index(fields=['is_active', 'is_deleted'], name='active_idx'),
        ),
        migrations.AddConstraint(
            model_name='childprofile',
            constraint=models.UniqueConstraint(fields=('child_id', 'guardian'), name='unique_child_guardian'),
        ),
        migrations.AddIndex(
            model_name='childinterest',
            index=models.Index(fields=['interest_id'], name='pk_idx'),
        ),
        migrations.AddIndex(
            model_name='childinterest',
            index=models.Index(fields=['is_active', 'is_deleted'], name='act_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['is_active', 'is_deleted'], name='active_deleted_idx'),
        ),
    ]
