# Generated by Django 6.0.1 on 2026-02-04 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_active_profile_childprofile_childinterest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childinterest',
            options={'ordering': ('-created_at',), 'verbose_name': 'Interest'},
        ),
        migrations.AlterModelOptions(
            name='childprofile',
            options={'ordering': ('-created_at',), 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
