# Generated by Django 6.0.1 on 2026-02-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_childinterest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='acitve_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_account', to='users.childprofile'),
        ),
    ]
