# Generated by Django 6.0.1 on 2026-02-05 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_acitve_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='acitve_account',
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_account', to='users.childprofile'),
        ),
    ]
