# Generated by Django 6.0.1 on 2026-02-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_acitve_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='raw_code',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
