# Generated by Django 6.0.1 on 2026-02-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_onetimepassword_raw_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='raw_code',
            field=models.CharField(db_index=True, default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
