# Generated by Django 6.0.1 on 2026-02-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_passwordreset_raw_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
