# Generated by Django 6.0.1 on 2026-02-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_instructor_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active_profile',
            field=models.CharField(blank=True, choices=[('CHILD', 'Child'), ('GUARDIAN', 'Guardian')], default=None, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='certificates',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_name_and_user'),
        ),
    ]
