# Generated by Django 6.0.1 on 2026-02-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_active_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
