# Generated by Django 6.0.1 on 2026-02-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_childprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default=None, max_length=200),
        ),
    ]
