# Generated by Django 6.0.1 on 2026-02-05 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0002_enrollment_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('content_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video'), ('FILE', 'File'), ('TEXT', 'Text')], default=None)),
                ('content_url', models.URLField(blank=True, null=True)),
                ('content_body', models.TextField(blank=True, null=True)),
                ('content_status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS')),
                ('content_order', models.PositiveIntegerField(default=1)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='skills.skills')),
            ],
            options={
                'db_table': 'lesson_contents',
                'ordering': ['content_order'],
                'indexes': [models.Index(fields=['skill', 'content_order'], name='lesson_cont_skill_i_f2a5ac_idx'), models.Index(fields=['skill', 'content_type'], name='lesson_cont_skill_i_dc3514_idx'), models.Index(fields=['is_active'], name='lesson_cont_is_acti_f6fff3_idx'), models.Index(fields=['is_completed'], name='lesson_cont_is_comp_3c4a4b_idx'), models.Index(fields=['content_status'], name='lesson_cont_content_ee4524_idx'), models.Index(fields=['current_level'], name='lesson_cont_current_1323e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('skill', 'content_order'), name='unique_content_order_per_skill')],
            },
        ),
    ]
