# Generated by Django 6.0.1 on 2026-02-16 15:31

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('content_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video'), ('FILE', 'File'), ('TEXT', 'Text')], default=None)),
                ('content_url', models.URLField(blank=True, null=True)),
                ('content_body', models.TextField(blank=True, null=True)),
                ('content_status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS')),
                ('content_order', models.PositiveIntegerField(default=1)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lesson_contents',
                'ordering': ['content_order'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progress_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('instructions', models.TextField()),
                ('requirements', models.TextField()),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('HARD', 'Hard'), ('MEDIUM', 'Medium')], default=None)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendation_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('recommendation_score', models.FloatField(help_text='confidence with recomendation')),
                ('category', models.CharField(max_length=200, null=True)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default=None)),
                ('reason', models.TextField(blank=True, null=True)),
                ('recommendation_type', models.CharField(blank=True, max_length=200, null=True)),
                ('recommended_by', models.CharField(choices=[('SYSTEM', 'System'), ('AI', 'AI')], max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('submission_type', models.CharField(choices=[('FILE', 'file'), ('TEXT', 'text'), ('URL', 'url')], default=None)),
                ('submission_text', models.TextField(null=True)),
                ('submission_file', models.URLField(null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'submitted'), ('APPROVED', 'approved'), ('REJECT', 'reject')], default=None)),
                ('feedback', models.TextField(null=True)),
                ('work_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=5)])),
                ('instructors_points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=10), django.core.validators.MaxValueValidator(limit_value=100)])),
                ('total_points_after_validatiokn', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
            },
        ),
    ]
