# Generated by Django 6.0.1 on 2026-02-07 21:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0001_initial'),
        ('skills', '0002_enrollment_purchase'),
        ('users', '0009_remove_customuser_acitve_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('instructions', models.TextField()),
                ('requirements', models.TextField()),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('HARD', 'Hard'), ('MEDIUM', 'Medium')], default=None)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='lesson_app.lessoncontent')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendation_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('recommendation_score', models.FloatField(help_text='confidence with recomendation')),
                ('category', models.CharField(max_length=200, null=True)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default=None)),
                ('reason', models.TextField(blank=True, null=True)),
                ('recommendation_type', models.CharField(max_length=200, null=True)),
                ('recommended_by', models.CharField(choices=[('SYSTEM', 'System'), ('AI', 'AI')], max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.childprofile')),
                ('skills', models.ManyToManyField(related_name='skills', to='skills.skills')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('submission_type', models.CharField(choices=[('FILE', 'file'), ('TEXT', 'text'), ('URL', 'url')], default=None)),
                ('submission_text', models.TextField(null=True)),
                ('submission_file', models.URLField(null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'submitted'), ('APPROVED', 'approved'), ('REJECT', 'reject')], default=None)),
                ('feedback', models.TextField(null=True)),
                ('work_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=5)])),
                ('instructors_points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=10), django.core.validators.MaxValueValidator(limit_value=100)])),
                ('total_points_after_validatiokn', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.childprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='lesson_app.projects')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progress_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('child_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='users.childprofile')),
                ('lesson_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lesson_app.lessoncontent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('child_profile', 'lesson_content'), name='unique_user_content')],
            },
        ),
        migrations.AddIndex(
            model_name='projects',
            index=models.Index(fields=['lesson_content'], name='projects_lesson__f8c6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='projects',
            index=models.Index(fields=['difficulty'], name='projects_difficu_d0cee6_idx'),
        ),
        migrations.AddIndex(
            model_name='projects',
            index=models.Index(fields=['is_active'], name='projects_is_acti_3457d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='projects',
            constraint=models.UniqueConstraint(fields=('lesson_content', 'title'), name='unique_project_title_per_lesson_content'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('child_profile', 'recommendation_type', 'category', 'difficulty'), name='unique_recommendation_per_child'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['project'], name='lesson_app__project_5a7f83_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['child_profile'], name='lesson_app__child_p_ad84db_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='lesson_app__status_748792_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('project', 'child_profile'), name='unique_submission_per_project_per_user'),
        ),
    ]
