# Generated by Django 6.0.1 on 2026-02-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_app', '0002_projects_recommendation_submission_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
