# Generated by Django 6.0.1 on 2026-02-16 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson_app', '0002_initial'),
        ('skills', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='child_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='users.childprofile'),
        ),
        migrations.AddField(
            model_name='progress',
            name='lesson_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lesson_app.lessoncontent'),
        ),
        migrations.AddField(
            model_name='projects',
            name='lesson_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='lesson_app.lessoncontent'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='child_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.childprofile'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='skills.skills'),
        ),
        migrations.AddField(
            model_name='submission',
            name='child_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.childprofile'),
        ),
        migrations.AddField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='lesson_app.projects'),
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['skill', 'content_order'], name='lesson_cont_skill_i_f2a5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['skill', 'content_type'], name='lesson_cont_skill_i_dc3514_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['is_active'], name='lesson_cont_is_acti_f6fff3_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['is_completed'], name='lesson_cont_is_comp_3c4a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['content_status'], name='lesson_cont_content_ee4524_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['current_level'], name='lesson_cont_current_1323e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessoncontent',
            constraint=models.UniqueConstraint(fields=('skill', 'content_order'), name='unique_content_order_per_skill'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('child_profile', 'lesson_content'), name='unique_user_content'),
        ),
        migrations.AddIndex(
            model_name='projects',
            index=models.Index(fields=['lesson_content'], name='projects_lesson__f8c6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='projects',
            index=models.Index(fields=['difficulty'], name='projects_difficu_d0cee6_idx'),
        ),
        migrations.AddIndex(
            model_name='projects',
            index=models.Index(fields=['is_active'], name='projects_is_acti_3457d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='projects',
            constraint=models.UniqueConstraint(fields=('lesson_content', 'title'), name='unique_project_title_per_lesson_content'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('child_profile', 'recommendation_type', 'category', 'difficulty'), name='unique_recommendation_per_child'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['project'], name='lesson_app__project_5a7f83_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['child_profile'], name='lesson_app__child_p_ad84db_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='lesson_app__status_748792_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('project', 'child_profile'), name='unique_submission_per_project_per_user'),
        ),
    ]
